const PropertiesTypes = {
  LIST_PROPERTIES_REQUEST: "LIST_PROPERTIES_REQUEST",
  LIST_PROPERTIES_ERROR: "LIST_PROPERTIES_ERROR",
  LIST_PROPERTIES_SUCCESS: "LIST_PROPERTIES_SUCCESS",
  CREATE_PROPERTY_REQUEST: "CREATE_PROPERTY_REQUEST",
  CREATE_PROPERTY_ERROR: "CREATE_PROPERTY_ERROR",
  CREATE_PROPERTY_SUCCESS: "CREATE_PROPERTY_SUCCESS",
  EDIT_PROPERTY_REQUEST: "EDIT_PROPERTY_REQUEST",
  EDIT_PROPERTY_ERROR: "EDIT_PROPERTY_ERROR",
  EDIT_PROPERTY_SUCCESS: "EDIT_PROPERTY_SUCCESS",
  DELETE_PROPERTY_REQUEST: "DELETE_PROPERTY_REQUEST",
  DELETE_PROPERTY_ERROR: "DELETE_PROPERTY_ERROR",
  DELETE_PROPERTY_SUCCESS: "DELETE_PROPERTY_SUCCESS",
  DETAIL_PROPERTY_REQUEST: "DETAIL_PROPERTY_REQUEST",
  DETAIL_PROPERTY_ERROR: "DETAIL_PROPERTY_ERROR",
  DETAIL_PROPERTY_SUCCESS: "DETAIL_PROPERTY_SUCCESS",
  UPDATE_PROPERTIES_FILTERS: "UPDATE_PROPERTIES_FILTERS",
  MARK_AS_SOLD_REQUEST: "MARK_AS_SOLD_REQUEST",
  MARK_AS_SOLD_ERROR: "MARK_AS_SOLD_ERROR",
  MARK_AS_SOLD_SUCCESS: "MARK_AS_SOLD_SUCCESS",
};

export default PropertiesTypes;
