const EmployeesTypes = {
  CREATE_EMPLOYEE_REQUEST: "CREATE_EMPLOYEE_REQUEST",
  CREATE_EMPLOYEE_ERROR: "CREATE_EMPLOYEE_ERROR",
  CREATE_EMPLOYEE_SUCCESS: "CREATE_EMPLOYEE_SUCCESS",
  DELETE_EMPLOYEE_REQUEST: "DELETE_EMPLOYEE_REQUEST",
  DELETE_EMPLOYEE_ERROR: "DELETE_EMPLOYEE_ERROR",
  DELETE_EMPLOYEE_SUCCESS: "DELETE_EMPLOYEE_SUCCESS",
  EMPLOYEES_LIST_REQUEST: "EMPLOYEE_LIST_REQUEST",
  EMPLOYEES_LIST_ERROR: "EMPLOYEE_LIST_ERROR",
  EMPLOYEES_LIST_SUCCESS: "EMPLOYEE_LIST_SUCCESS",
};

export default EmployeesTypes;
