const BookingsTypes = {
  //BOOKINGS_REQUEEST: 'BOOKINGS_REQUEEST',
  BOOKINGS_ACCEPT: "BOOKINGS_ACCEPT",
  BOOKINGS_PENDING: "BOOKINGS_PENDING",
  BOOKINGS_DENY: "BOOKINGS_DENY",
  BOOKINGS_SUCCESS: "BOOKINGS_SUCCESS",
};

export default BookingsTypes;
